MODEL:
  NAME: 'resnet50'
  BACKBONE_EMB_SIZE: 2048
  PRETRAIN_PATH: './models/resnet50-19c8e357.pth'
  KEEP_CAMID_CENTROIDS: True

INPUT:
  SIZE_TRAIN: [256,128]
  SIZE_TEST: [256,128]

DATALOADER:
  NUM_INSTANCE: 4
  USE_RESAMPLING: False

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.00035
  OPTIMIZER_NAME: "Adam"
  MAX_EPOCHS: 120
  EVAL_PERIOD: 40

USE_MIXED_PRECISION: False

REPRODUCIBLE_NUM_RUNS: 1

GPU_IDS: [0] 

DATASETS:
  NAMES: 'last'
  ROOT_DIR: './datasets/data/'
  VERBOSE: True

TEST:
  IMS_PER_BATCH: 128
  ONLY_TEST: False

OUTPUT_DIR: './logs/last/256_resnet50/'